CREATE TABLE  "PERSON" 
   (	"PERSONID" NUMBER NOT NULL ENABLE, 
	"FIRSTNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LASTNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"INFO" VARCHAR2(50), 
	 CONSTRAINT "PERSON_PK" PRIMARY KEY ("PERSONID") ENABLE
   )
/


INSERT INTO PERSON (PERSONID, FIRSTNAME, LASTNAME, INFO) VALUES ('1', 'Chad', 'Miller', 'Project Owner');
INSERT INTO PERSON (PERSONID, FIRSTNAME, LASTNAME, INFO) VALUES ('2', 'Brend', 'Kriszio', NULL);
INSERT INTO PERSON (PERSONID, FIRSTNAME, LASTNAME, INFO) VALUES ('3', 'Mike', 'Shepard', 'AdoLib');
INSERT INTO PERSON (PERSONID, FIRSTNAME, LASTNAME, INFO) VALUES ('4', 'Max', 'Trinidad', NULL);
INSERT INTO PERSON (PERSONID, FIRSTNAME, LASTNAME, INFO) VALUES ('5', 'Steve', 'Murawski', NULL);